import type { Metadata } from 'next';
import './globals.css';
import Providers from "@/providers/LayoutWrapper";
import publicSans from "./fonts"
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${publicSans.className} antialiased`}>
        <Providers>{children}
        </Providers>
        <Toaster/>
      </body>
    </html>
  );
}
